#server:
#  port: 8014
#spring:
#  application:
#    name: api-order-submit
#  redis:
#    port: 7001
#    host: 8.130.77.18
#    database: 0
#    password: lengdi123
#  rabbitmq:
#    host: 8.130.77.18
#    port: 15672
#    virtual-host: host1
#    username: zhangsan
#    password: lengdi123
#eureka:
#  client:
#    service-url:
#      defaultZone: http://zhangsan:123456@localhost:8761/eureka
#feign:
#  hystrix:
#    enabled: true

spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: api-order-submit
      label: master