server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lengdi777/sdmall-config.git
          search-paths: files
          username: lengdi785@163.com
          password: lsd41271
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka